sudo: required

language: generic

services:
- docker

before_install:
- docker info
- docker pull java:openjdk-8-jre
- docker pull java:openjdk-8-jre-alpine

script:
- bash build-all.sh versions build_all test_all push_all
